### ISSUE TITLE
How to filter results by North America only?

### ISSUE THREAD

**Issue by justinrbrower** [JackieDo/Timezone-List#14]
We are currently filtering by "option value="America/"  which does a great job to reduce the available outputs however this is still 147 timezones approximately. 

How can we reduce this even further to show only North America or another country for example?

**Comment by JackieDo** [comment]
@justinrbrower :

Dear friend.

At the time you submitted this post, this package did not have a method to make it easier. But thanks to your request, I got some additional ideas for the working methods of the package.

Now, from version `5.1.x`, this package has added some methods to help you do that. Please update it and read more instructions [here](https://github.com/JackieDo/Timezone-List/tree/5.x#filter-the-returned-list).
